#发布订阅制，各个模块通过发布消息、订阅消息来交互信息
#TODO: 
#文件监控模块，大量异常后缀变动告警（勒索病毒）、文件夹内容变动提醒（共享文件夹变动提示）
#性能监控模块，cpu、内存突然暴涨告警（挖矿）、达到阈值自动执行内存优化
#处置模块，根据告警和预定义动作，对告警进行处置，可能尝试集成少量高危特征库

# 模块列表，根据开发进度添加模块名和模块自定义配置
# memopt，内存优化模块
# sysTray，托盘模块
# fileMonitor，文件管理模块（待实现）
modules:
  memopt
  sysTray 
  fileMonitor

# 对应模块配置，是否开启、运行时间等配置，可扩展配置结构
# 内存优化模块
memopt:
  enabled: false
  interval: 60 # 运行间隔，单位秒

# 系统托盘模块
sysTray:
  enabled: true

# 文件监控模块（待实现）
fileMonitor:
  enabled: false
  interval: 20 # 运行间隔，单位秒
  file_path: C:// # 监控的文件路径  
